import type { User } from '~/types/user'

export default defineEventHandler((event) => {
    return [
        {
            id: 1,
            name: 'Admin User',
            email: 'admin@ssgh.ph',
            role: 'Administrator',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 08:00 AM'
        },
        {
            id: 2,
            name: 'Dr. Maria Rivera',
            email: 'm.rivera@ssgh.ph',
            role: 'Supervisor',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 07:30 AM'
        },
        {
            id: 3,
            name: 'Nurse Ana Bautista',
            email: 'a.bautista@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 07:00 AM',
            code: 'AGT001',
            transaction: 'Consultation',
            agentStatus: 'Online',
            counter: 'Counter 1',
            ticket: 'A-101',
            served: 12,
            avgService: '5:30',
            dateAssigned: 'Mar 16, 2026, 08:00 AM',
            dateUpdated: 'Mar 16, 2026, 09:30 AM',
            schedule: 'Morning (7:00 AM - 3:00 PM)'
        },
        {
            id: 4,
            name: 'Mr. Jose Villanueva',
            email: 'j.villanueva@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 08:00 AM',
            code: 'AGT002',
            transaction: 'Billing',
            agentStatus: 'Serving',
            counter: 'Counter 2',
            ticket: 'B-205',
            served: 8,
            avgService: '7:15',
            dateAssigned: 'Mar 16, 2026, 08:00 AM',
            dateUpdated: 'Mar 16, 2026, 10:15 AM',
            schedule: 'Afternoon (3:00 PM - 11:00 PM)'
        },
        {
            id: 5,
            name: 'Ms. Clara Santiago',
            email: 'c.santiago@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 07:00 AM',
            code: 'AGT003',
            transaction: 'Admission',
            agentStatus: 'On Break',
            counter: 'Counter 3',
            ticket: '-',
            served: 15,
            avgService: '4:45',
            dateAssigned: 'Mar 15, 2026, 09:30 AM',
            dateUpdated: 'Mar 21, 2026, 11:30 AM',
            schedule: 'Morning (7:00 AM - 3:00 PM)'
        },
        {
            id: 6,
            name: 'Mr. Ramon Aquino',
            email: 'r.aquino@ssgh.ph',
            role: 'Agent',
            status: 'Suspended',
            lastLogin: 'Mar 15, 2026, 04:00 PM',
            code: 'AGT004',
            transaction: 'Outpatient',
            agentStatus: 'Offline',
            counter: '-',
            ticket: '-',
            served: 0,
            avgService: '0:00',
            dateAssigned: 'Mar 15, 2026, 11:00 AM',
            dateUpdated: 'Mar 20, 2026, 05:30 PM'
        },
        {
            id: 7,
            name: 'Ms. Elena Cruz',
            email: 'e.cruz@ssgh.ph',
            role: 'Supervisor',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 09:00 AM'
        },
        {
            id: 8,
            name: 'Mr. Roberto Gomez',
            email: 'r.gomez@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 08:45 AM',
            code: 'AGT005',
            transaction: 'Outpatient',
            agentStatus: 'Online',
            counter: 'Counter 4',
            ticket: 'C-302',
            served: 21,
            avgService: '4:55',
            dateAssigned: 'Mar 16, 2026, 08:15 AM',
            dateUpdated: 'Mar 21, 2026, 11:30 AM'
        },
        {
            id: 9,
            name: 'Dr. Francis Santos',
            email: 'f.santos@ssgh.ph',
            role: 'Administrator',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 10:00 AM'
        },
        {
            id: 10,
            name: 'Nurse Laila Reyes',
            email: 'l.reyes@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 06:30 AM',
            code: 'AGT006',
            transaction: 'Billing',
            agentStatus: 'Serving',
            counter: 'Counter 5',
            ticket: 'D-404',
            served: 19,
            avgService: '5:45',
            dateAssigned: 'Mar 16, 2026, 07:50 AM',
            dateUpdated: 'Mar 21, 2026, 04:20 PM'
        },
        {
            id: 11,
            name: 'Mr. Antonio Luna',
            email: 'a.luna@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 11:00 AM',
            code: 'AGT007',
            transaction: 'Consultation',
            agentStatus: 'Online',
            counter: 'Counter 6',
            ticket: '-',
            served: 5,
            avgService: '6:30'
        },
        {
            id: 12,
            name: 'Ms. Patricia Lim',
            email: 'p.lim@ssgh.ph',
            role: 'Supervisor',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 08:15 AM'
        },
        {
            id: 13,
            name: 'Mr. Miguel Ramos',
            email: 'm.ramos@ssgh.ph',
            role: 'Agent',
            status: 'Suspended',
            lastLogin: 'Mar 14, 2026, 02:00 PM',
            code: 'AGT008',
            transaction: 'Admission',
            agentStatus: 'Offline',
            counter: '-',
            ticket: '-',
            served: 0,
            avgService: '0:00'
        },
        {
            id: 14,
            name: 'Dr. Sarah Tan',
            email: 's.tan@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 12:00 PM',
            code: 'AGT009',
            transaction: 'Outpatient',
            agentStatus: 'Online',
            counter: 'Counter 7',
            ticket: 'E-505',
            served: 10,
            avgService: '5:15'
        },
        {
            id: 15,
            name: 'Nurse Kevin Lee',
            email: 'k.lee@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 05:00 AM',
            code: 'AGT010',
            transaction: 'Billing'
        },
        {
            id: 16,
            name: 'Ms. Jasmine Diaz',
            email: 'j.diaz@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 01:00 PM',
            code: 'AGT011',
            transaction: 'Consultation'
        },
        {
            id: 17,
            name: 'Mr. David Wilson',
            email: 'd.wilson@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 02:30 PM',
            code: 'AGT012',
            transaction: 'Admission'
        },
        {
            id: 18,
            name: 'Ms. Linda Garcia',
            email: 'l.garcia@ssgh.ph',
            role: 'Supervisor',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 03:45 PM'
        },
        {
            id: 19,
            name: 'Mr. Peter Parker',
            email: 'p.parker@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 04:00 PM',
            code: 'AGT013',
            transaction: 'Billing'
        },
        {
            id: 20,
            name: 'Ms. Mary Jane Watson',
            email: 'mj.watson@ssgh.ph',
            role: 'Agent',
            status: 'Active',
            lastLogin: 'Mar 16, 2026, 04:15 PM',
            code: 'AGT014',
            transaction: 'Outpatient'
        }
    ] as User[]
})
